data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/plier_clipping_success
process_single_demo: false

# Preprocessing for different types - if both false then preprocessing is done for deployment
vision_byol: false
tactile_byol: false

subsample_separately: true

# TODO: Separate the robots, should make this automatically
kinova_threshold_step_size: 0.012 # If subsample_separately set to true this will be used
allegro_threshold_step_size: 0.008 
threshold_step_size: null # 0.012 # Step size to be used in subsampling

# TODO: All of these could be done in a class - might be better that way!
preprocessing_types: ['image', 'tactile', 'kinova', 'allegro'] # Should change the names as it goes
dump_images: true # If set to true it dumps the images that will be used from the data indices
dump_data_indices: true 
dump_fingertips: true

view_num: 0 # Camera ID to dump the images


# preprocessor:
#   arm: arm_cfg
#   hand: hand_cfg
#   image: image_cfg
#   touch: touch_cfg

# arm_cfg:
#   name: allegro
#   type: arm
#   file



human_data:
  apply: false 
  time_difference: 0.3

shorten_demo:
  apply: false 
  # Times in seconds for each demo - if only one value is given then we'll only use that
  times: [0.0, 2, 3]

repr_preprocessor: # NOTE: This was for BET  and IBC - we're just getting the representations in bet
  apply: false
  tactile_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.01.28/12-32_tactile_byol_bs_512_tactile_play_data_alexnet_pretrained_duration_120
  # Cup unstacking 
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.04.05/00-59_image_byol_bs_32_cup_picking_after_rss
  # demos_to_use: [13,14,15,16,17,18]
  # Bowl unstacking
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.06/10-50_image_byol_bs_32_epochs_500_lr_1e-05_bowl_picking_after_rss
  # demos_to_use: [22,24,26,34,28,29]
  # Bottle Opening
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.09/17-10_image_byol_bs_32_epochs_500_lr_1e-05_bottle_opening_after_rss 
  # demos_to_use: [2,5,8,10,11,12] 
  # Gamepad
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/00-13_image_byol_bs_32_epochs_500_lr_1e-05_gamepad_after_rss 
  # demos_to_use: [2,3,5,6,7,9] 
  # Book Opening
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.05.10/16-16_image_byol_bs_33_epochs_500_lr_1e-05_book_opening_after_rss 
  # demos_to_use: [3,4,5,6,8,10] 

  # CORL
  # Bowl Picking
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.06/18-27_temporal_ssl_bs_32_epochs_1000_view_1_bowl_picking_frame_diff_5_resnet
  # image_model_type: temporal

  # Plier picking
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.02/21-37_temporal_ssl_bs_32_epochs_1000_lr_1e-05_plier_picking_frame_diff_8
  
  # Peg insertion
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.06/22-59_temporal_ssl_bs_32_epochs_1000_view_0_peg_insertion_frame_diff_5_resnet 
  
  # Card Turning
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.05/19-59_temporal_ssl_bs_32_epochs_1000_lr_1e-05_card_turning_frame_diff_5_resnet 
  
  # Card Flipping
  # image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.04/21-28_temporal_ssl_bs_32_epochs_1000_lr_1e-05_card_flipping_frame_diff_5_resnet 
  # image_model_type: temporal
  # demos_to_use: []

  # Mint Opening 
  image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.14/17-53_temporal_ssl_bs_32_epochs_1000_view_0_mint_opening_frame_diff_5_resnet
  image_model_type: temporal
  demos_to_use: []

  representation_types: ['image','tactile','kinova','allegro']