_target_: tactile_learning.datasets.TactileSSLDataset
data_path: ???
tactile_information_type: whole_hand # whole_hand, stacked, single_sensor
tactile_img_size: ${tactile_image_size} 
duration: 120 # All durations: 5, 10, 20, 40, 60, 80, 100, 120
# shuffle_type: pad
# Stats for the play data
# mean_std: # These values should be found through notebook
#   - [-3.4821,  0.8840, 11.0220]
#   - [96.1595, 67.3064, 72.4123]
# min_max: 
#   - [ -5.9464, -10.1432,  -9.6585] # After clamping min and max
#   - [ 5.9450, 10.1289,  9.4191]