# TAVI
image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.04/21-28_temporal_ssl_bs_32_epochs_1000_lr_1e-05_card_flipping_frame_diff_5_resnet
image_model_type: temporal

# Joint Temporal
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/15-13_temporal_ssl_card_turning_view_0_joint_resnet
# image_model_type: temporal

# Contrastive Temporal
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/14-21_temporal_ssl_card_turning_view_0_contrastive_resnet
# image_model_type: temporal

# BYOL
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/17-44_image_byol_card_turning_view_0_resnet
# image_model_type: byol

# BC 
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/21-37_bc_card_turning_view_0_resnet
# image_model_type: bc

# image_out_dir: null
# image_model_type: pretrained

vinn_image_out_dir: 2023.06.07-17-45_image_byol_card_flipping_view_0_resnet
vinn_image_model_type: byol

data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/human_sponge_flipping
robot_data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/card_flipping

name: human_sponge_flipping
task_name: CardFlipping-v1
action_type: human
camera_num: 0

expert_demo_nums: [7]
robot_demo_nums: [24]

arm_offset_scale_factor: 0.05
hand_offset_scale_factor: 0.25 #sponge flipping
# offset_mask: [0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0] # sponge flipping
# offset_mask: [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] # sponge flipping
offset_mask: [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
