image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.06/22-59_temporal_ssl_bs_32_epochs_1000_view_0_peg_insertion_frame_diff_5_resnet # peg insertion 
image_model_type: temporal # TODO: Add this information to the config - or get it from the learner type and etc

# joint
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/14-40_temporal_ssl_peg_insertion_view_0_joint_resnet
# image_model_type: temporal

#constrastive
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/15-05_temporal_ssl_peg_insertion_view_0_contrastive_resnet
# image_model_type: temporal

#BYOL
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/18-38_image_byol_peg_insertion_view_0_resnet
# image_model_type: byol

#BC
# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.07/21-18_bc_peg_insertion_view_0_resnet
# image_model_type: bc

#pretrained
# image_out_dir: null 
# image_model_type: pretrained

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /home/irmak/Workspace/Holo-Bot/extracted_data/peg_insertion

name: peg_insertion
task_name: PegInsertion-v1
camera_num: 0

expert_demo_nums: [4]
arm_offset_scale_factor: 0.05
hand_offset_scale_factor: 0.07

offset_mask: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] # peg insertion

action_type: robot